version: '3'
services:
  frontend:
    image: nginx:latest
    ports:
      - 8000:80
      - 8443:443
    volumes:
      - ./website:/usr/share/nginx/html
      - ./nconfig/:/nginx/config/

  mqqt-broker:
    image: eclipse-mosquitto:2
    ports:
      - 9494:1884
      - 8383:1883
    volumes:
      - ./config/:/mosquitto/config/
      - ./log/:/mosquitto/log/
      - ./data:/mosquitto/data/